name: build_test

on: [pull_request, push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      GCC_V: 12

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8

    - name: Install dependencies
      if: contains( matrix.os, 'ubuntu')
      run: |
        sudo apt update
        sudo apt install -yq curl unzip git make cmake gfortran mpich liblapack-dev libsymspg-dev
        sudo apt clean -q
        git clone https://github.com/sourceryinstitute/OpenCoarrays && \
        mkdir OpenCoarrays/opencoarrays-install  && \
        cd OpenCoarrays/opencoarrays-install && \
        git checkout tags/2.10.1 && \
        FC="$(command -v gfortran)" CC="$(command -v gcc)" cmake .. && \
        sudo make install && \
        caf --version && \
        cafrun --version
        
    - name: Build with CMake
      run: |
        mkdir cmake-build; cd cmake-build
        cmake ..; make; ctest
        cat /home/runner/work/elphbolt/elphbolt/cmake-build/Testing/Temporary/LastTest.log
